### ISSUE TITLE
Update Documentation for Real Dev Squad Apps

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/docs#17]
# Update Documentation for Real Dev Squad Apps

**Doc link** : https://github.com/Real-Dev-Squad/docs/edit/main/docs/apps/README.md

**Description:**
The documentation for Real Dev Squad apps needs to be updated with the latest information. This includes updating the repository links, staging and production links, and any additional notes for each app like - 

| Name   | Repo Link           | Staging Link                       | Prod Link                          | Note    |
|--------|---------------------|------------------------------------|------------------------------------|---------|
| www    | [Repo Link]         | [Staging Link]                     | [Prod Link]                        | Tech used, deployed server name etc. |

Please update the documentation accordingly. Once the updates are made, close this issue.

**Comment by pronoyb07** [comment]
Hey @sahsisunny I'd like to take this task

**Comment by pronoyb07** [comment]
Hey @sahsisunny I'd like to take this task, can you please assign this to me
